---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: singapore-booking
spec:
  timeZone: 'Asia/Singapore'
  schedule: "14 07 * * 4"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: singapore-booking
              args: [-start=8]
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: singapore-booking-login
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: singapore-booking-login
                  key: PASSWORD
