---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: singapore-booking
spec:
  timeZone: 'Asia/Singapore'
  jobTemplate:
    spec:
      template:
        spec:
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: singapore-booking-login
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: singapore-booking-login
                  key: PASSWORD
