apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: jellyseerr
spec:
  interval: 1h
  url: oci://ghcr.io/fallenbagel/jellyseerr/jellyseerr-chart
  timeout: 3m
  ref:
    semver: ">=2.x"
