apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/rancher/local-path-provisioner
  ref:
    # pin to a stable release
    tag: v0.0.31
