apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    background: 
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 50 # 0-100
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Jellyfin:
        - Jellyfin:
            href: https://jellyfin.tail537360.ts.net/web/
            description: Watch Movies and TV Shows
    - Seerr:
        - Seerr:
            href: https://seerr.tail537360.ts.net/
            description: Request Movies and TV Shows
    - Radaarr:
        - Radaarr:
            href: https://rafarr.tail537360.ts.net/
            description: Automated Movie Collection Manager
    - Sonarr:
        - Sonarr:
            href: https://sonarr.tail537360.ts.net/
            description: Automated TV Collection Manager
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
