apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: waha-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: waha-secrets
    creationPolicy: Owner
  data:
    - secretKey: WAHA_API_KEY
      remoteRef:
        key: WAHA_API_KEY
    - secretKey: WAHA_DASHBOARD_PASSWORD
      remoteRef:
        key: WAHA_DASHBOARD_PASSWORD