apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: AUTHENTIK_SECRET_KEY
        property: value
    - secretKey: postgresql_password
      remoteRef:
        key: AUTHENTIK_POSTGRESQL_PASSWORD
        property: value
    - secretKey: redis_password
      remoteRef:
        key: AUTHENTIK_REDIS_PASSWORD
        property: value