apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openrouter-api-key
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  target:
    name: openrouter-api-key
    creationPolicy: Owner
  data:
    - secretKey: OPENROUTER_API_KEY
      remoteRef:
        key: OPENROUTER_API_KEY
