---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: singapore-booking
spec:
  jobTemplate:
    metadata:
      labels:
        app: singapore-booking
    spec:
      template:
        spec:
          containers:
            - name: singapore-booking
              image: ghcr.io/tomythical/selenium-automation:main
              imagePullPolicy: Always
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never
