apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  interval: 1h
  chart:
    spec:
      chart: n8n
      sourceRef:
        kind: HelmRepository
        name: n8n-charts
        namespace: flux-system
  values:
    main:
      count: 1
      persistence:
        enabled: true
        storageClass: local-path
        size: 8Gi

    service:
      annotations:
        tailscale.com/expose: "true"

    worker:
      persistence:
        enabled: true
        storageClass: local-path
        size: 8Gi

    serviceMonitor:
      enabled: true
      namespace: monitoring
      labels:
        release: kube-prometheus-stack
      timeout: 10s
      targetLabels: []
