apiVersion: apps/v1
kind: Deployment
metadata:
  name: instaloader
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instaloader
  template:
    metadata:
      labels:
        app: instaloader
    spec:
      containers:
        - name: instaloader
          image: ghcr.io/tomythical/instaloader:latest
          ports:
            - containerPort: 5633
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5633
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5633
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: workflows-pvc
              mountPath: /tmp
      volumes:
        - name: workflows-pvc
          persistentVolumeClaim:
            claimName: workflows-pvc
