apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
spec:
  interval: 1h
  chart:
    spec:
      chart: ./deploy/chart/local-path-provisioner/
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
