apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 1h
  prune: false
  sourceRef:
    kind: GitRepository
    name: metallb-crds
  path: "./charts/metallb/charts/crds"
  validation: client

