apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent-crds
  namespace: kagent
spec:
  interval: 3m
  chart:
    spec:
      chart: kagent-crds
      version: 0.7.4
      sourceRef:
        kind: HelmRepository
        name: kagent-chart
        namespace: flux-system
      interval: 5m
