apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-api-key
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  target:
    name: sonarr-api-key
  data:
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: SONARR_API_KEY
