---
# Source: k8s-mediaserver/templates/storage-resources.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr-config
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
