apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pomerium-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  target:
    name: pomerium
    creationPolicy: Owner
  data:
    - secretKey: pomerium_zero_token
      remoteRef:
        key: POMERIUM_TOKEN