apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent-crds
  namespace: infra
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: kagent-crds-chart
    namespace: flux-system
