apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
  namespace: infra
spec:
  interval: 10m
  chart:
    spec:
      chart: kagent
      sourceRef:
        kind: OCIRepository
        name: kagent-chart
        namespace: flux-system
  values:
    providers:
      openAI:
        apiKey: "<YOUR_OPENROUTER_API_KEY>"
        baseURL: "https://openrouter.ai/api/v1"
    agents:
      kgateway-agent:
        enabled: false
      istio-agent:
        enabled: false
      promql-agent:
        enabled: true
      observability-agent:
        enabled: true
      argo-rollouts-agent:
        enabled: false
      helm-agent:
        enabled: true
      cilium-policy-agent:
        enabled: false
      cilium-manager-agent:
        enabled: false
      cilium-debug-agent:
        enabled: false
    tools:
      grafana-mcp:
        enabled: true
      querydoc:
        enabled: false
