apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/singapore-booking/overlays/vaishali-tuesday/
  - ../../apps/singapore-booking/overlays/vaishali-friday/
  - ../../apps/singapore-booking/overlays/yazad-tuesday/
  - ../../apps/singapore-booking/overlays/yazad-friday/
