apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-server
resources:
  - pvc.yaml
  - secret-store.yaml
  - jellyseerr/
  - jellyfin/
  - prowlarr/
  - radarr/
  - sabnzbd/
  - sonarr/
  - recyclarr/
  - pinchflat/
  - streamystats/
