apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-mediaserver
spec:
  install:
    timeout: 5m0s
  upgrade:
    timeout: 5m0s
  interval: 1h
  chart:
    spec:
      chart: ./helm-charts/k8s-mediaserver
      sourceRef:
        kind: GitRepository
        name: k8s-mediaserver-operator
        namespace: flux-system
  values:
    general:
      ingress_host: media.local
      plex_ingress_host: plex.local
      jellyfin_ingress_host: jellyfin.local
      storage:
        customVolume: false
        pvcName: mediaserver-rwo-pvc
        size: 500Gi
        pvcStorageClass: local-path
        accessMode: ReadWriteOnce

    plex:
      enabled: false

    transmission:
      enabled: false

    jackett:
      enabled: false

    sonarr:
      enabled: true
      service:
        type: ClusterIP
        port: 8989
        extraLBService: false
        extraLBAnnotations: {}
        # Defines an additional LB service, requires cloud provider service or MetalLB
      ingress:
        enabled: false
        annotations: {}
        path: /sonarr
        tls:
          enabled: false
          secretName: ""
      resources: {}
      volume:
        name: pvc-sonarr-config
        storageClassName: local-path
        accessModes: ReadWriteOnce
        storage: 1Gi

    radarr:
      enabled: true
      service:
        type: ClusterIP
        port: 7878
        # Defines an additional LB service, requires cloud provider service or MetalLB
        extraLBService: false
        extraLBAnnotations: {}
      ingress:
        enabled: false
        annotations: {}
        path: /radarr
        tls:
          enabled: false
          secretName: ""
      resources: {}
      volume:
        name: pvc-radarr-config
        storageClassName: local-path
        accessModes: ReadWriteOnce
        storage: 1Gi

    sabnzbd:
      enabled: true
      container:
        port:
          http: 8080
          https: 9090
      service:
        http:
          type: ClusterIP
          port: 8080
          extraLBService: false
          extraLBAnnotations: {}
        https:
          type: ClusterIP
          port: 9090
          extraLBService: false
          extraLBAnnotations: {}
      ingress:
        enabled: false
        annotations: {}
        path: /sabnzbd
        tls:
          enabled: false
          secretName: ""
      resources: {}
      volume:
       name: pvc-sabnzbd-config
       storageClassName: local-path
       accessModes: ReadWriteOnce
       storage: 1Gi

    prowlarr:
      enabled: true
      service:
        type: ClusterIP
        port: 9696
        extraLBService: false
        extraLBAnnotations: {}
      ingress:
        enabled: false
        annotations: {}
        path: /prowlarr
        tls:
          enabled: false
          secretName: ""
      resources: {}
      volume:
       name: pvc-prowlarr-config
       storageClassName: local-path
       accessModes: ReadWriteOnce
       storage: 1Gi

    jellyfin:
      enabled: true
      service:
        type: ClusterIP
        port: 8096
        # Defines an additional LB service, requires cloud provider service or MetalLB
        extraLBService: false
      ingress:
        enabled: false
        annotations: {}
        tls:
          enabled: false
          secretName: ""
      resources: {}
      volume:
       name: pvc-jellyfin-config
       storageClassName: local-path
       accessModes: ReadWriteOnce
       storage: 1Gi
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Service
              name: radarr
            patch: |
              - op: add
                path: /metadata/annotations/tailscale.com~1expose
                value: "true"
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Service
              name: sonarr
            patch: |
              - op: add
                path: /metadata/annotations/tailscale.com~1expose
                value: "true"
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Service
              name: sabnzbd
            patch: |
              - op: add
                path: /metadata/annotations/tailscale.com~1expose
                value: "true"
