apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-api-keys
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  target:
    name: recyclarr-api-keys
dataFrom:
  - find:
      path: /
