---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: singapore-booking
spec:
  schedule: "57 06 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: singapore-booking
              args: [-start=8]
