apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 10m
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      persistence:
        enabled: true
        type: sts
        storageClassName: "local-path"
        accessModes:
          - ReadWriteOnce
        size: 10Gi
    prometheus:
      prometheusSpec:
        retentionSize: "40GB"
        retention: "30d"
        securityContext:
          runAsUser: 1000
          runAsGroup: 2000
          fsGroup: 2000
          runAsNonRoot: true
        initContainers:
          - name: fix-permissions
            image: busybox
            command: ["sh", "-c", "chown -R 1000:2000 /prometheus"]
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: prometheus-kube-prometheus-stack-prometheus-db
                mountPath: /prometheus
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: "local-path"
              resources:
                requests:
                  storage: 50Gi
