apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 10m
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      adminPassword: admin
      persistence:
        enabled: true
        type: sts
        storageClassName: "local-path"
        accessModes:
          - ReadWriteOnce
        size: 10Gi
      podSecurityContext:
        fsGroup: 472
      containerSecurityContext:
        runAsUser: 472
        runAsGroup: 472
      initChownData:
        enabled: false
    prometheus:
      prometheusSpec:
        retentionSize: "40GB"
        retention: "30d"
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
          runAsNonRoot: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: "local-path"
              resources:
                requests:
                  storage: 50Gi
