FROM ghcr.io/kieraneglin/pinchflat:latest

# Update yt-dlp to latest
RUN curl -L -o /usr/local/bin/yt-dlp \
  https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp && \
  chmod +x /usr/local/bin/yt-dlp
