apiVersion: v1
kind: Service
metadata:
  name: pinchflat
  namespace: media-server
spec:
  type: ClusterIP
  ports:
  - name: pinchflat-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pinchflat
