apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wizarr-config
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path