apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: fix-jellyfin-perms
          image: busybox
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              set -e
              # create and fix ownership for mount points
              mkdir -p /config
              chown -R 1000:1000 /config
              chmod -R 775 /config
          volumeMounts:
            - name: pvc-jellyfin-config
              mountPath: /config
      containers:
        - name: k8s-mediaserver
          image: docker.io/linuxserver/jellyfin:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: jellyfin-config
          readinessProbe:
            tcpSocket:
              port: 8096
            initialDelaySeconds: 20
            periodSeconds: 15
          ports:
            - name: jellyfin-port
              containerPort: 8096
              protocol: TCP
          volumeMounts:
            - name: pvc-jellyfin-config
              mountPath: /config
            - name: mediaserver-volume
              mountPath: /data
            - name: dri
              mountPath: /dev/dri
              readOnly: true
      volumes:
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: mediaserver-rwo-pvc
        - name: pvc-jellyfin-config
          persistentVolumeClaim:
            claimName: pvc-jellyfin-config
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
