apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-ts-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: jellyfin-ts-secret
    creationPolicy: Owner
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: JELLYFIN_TS_SECRET
