# Source: k8s-mediaserver/templates/sabnzbd-resources.yml
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media-server
  labels:
    app: sabnzbd
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-media-dirs
          image: busybox
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              set -e
              mkdir -p /data/sabnzbd/complete
              mkdir -p /data/sabnzbd/incomplete
              chown -R 1000:1000 /data
              chmod -R 775 /data
          volumeMounts:
            - name: mediaserver-volume
              mountPath: /data
        - name: config-sabnzbd
          image: docker.io/ubuntu:groovy
          command: [/init-sabnzbd/init-sabnzbd.sh]
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - mountPath: /init-sabnzbd
              name: init-files-sabnzbd
            - name: pvc-sabnzbd-config
              mountPath: /sabnzbd-config
      containers:
        - name: k8s-mediaserver
          image: docker.io/linuxserver/sabnzbd:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: sabnzbd-config
          ports:
            - name: sabnzbd-http
              containerPort: 8080
              protocol: TCP
            - name: sabnzbd-https
              containerPort: 9090
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /sabnzbd/wizard/
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 20
          volumeMounts:
            - name: pvc-sabnzbd-config
              mountPath: /config
            - name: mediaserver-volume
              mountPath: /data
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: mediaserver-rwo-pvc
        - name: pvc-sabnzbd-config
          persistentVolumeClaim:
            claimName: pvc-sabnzbd-config
        - name: init-files-sabnzbd
          configMap:
            defaultMode: 493
            name: init-sabnzbd-cm
