apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: streamystats-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  target:
    name: streamystats-secrets
    creationPolicy: Owner
  data:
    - secretKey: SESSION_SECRET
      remoteRef:
        key: SESSION_SECRET
    - secretKey: NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
      remoteRef:
        key: NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
