apiVersion: v1
kind: Secret
metadata:
  name: streamystats-postgres
  namespace: media-server
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: streamystats
