apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
        namespace: flux-system
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.68.10
    ports:
      web:
        entryPoint: http
        exposedPort: 80
      websecure:
        entryPoint: https
        exposedPort: 443
    dashboard:
      enabled: true
      domain: traefik.local
