---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
  - name: infra
  interval: 10m0s
  path: ./cluster/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
