
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: namespaces
    namespace: flux-system
  interval: 10m0s
  wait: true
  timeout: 5m
  retryInterval: 2m
  path: ./cluster/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
