---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-serverß
  namespace: flux-system
spec:
  dependsOn:
  - name: infra
    namespace: flux-system
  interval: 10m0s
  wait: true
  timeout: 5m
  retryInterval: 2m
  path: ./cluster/media-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
