---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  dependsOn:
  - name: crds
  interval: 10m0s
  path: ./cluster/namespaces
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
