apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metal-lb
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        version: 0.15.2
        kind: HelmRepository
        name: metal-lb-repo
        namespace: flux-system
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    speaker:
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: true
        allowPrivilegeEscalation: true
      ignoreExcludeLB: true
