apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metal-lb
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "0.15.2"
      sourceRef:
        kind: HelmRepository
        name: metal-lb-repo
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: Create
  values:
    speaker:
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: true
        allowPrivilegeEscalation: true
      ignoreExcludeLB: true
