apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metal-lb
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metal-lb-repo
        namespace: flux-system
  interval: 5m
  values:
    speaker:
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: true  # Allow privileged mode to bypass restrictions
        allowPrivilegeEscalation: true
