apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: padel-booking-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  target:
    name: padel-booking-secrets
    creationPolicy: Owner
  data:
    - secretKey: PADEL_PASSWORD
      remoteRef:
        key: PADEL_PASSWORD