apiVersion: v1
kind: Service
metadata:
  name: padel-booking
spec:
  selector:
    app: padel-booking
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
      name: restate
  type: ClusterIP