apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: journiv-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  target:
    name: journiv-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: JOURNIV_SECRET
    - secretKey: POSTGRES_USER
      remoteRef:
        key: JOURNIV_POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: JOURNIV_POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: JOURNIV_POSTGRES_DB
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: JOURNIV_POSTGRES_HOST
    - secretKey: DATABASE_URL
      remoteRef:
        key: JOURNIV_DATABASE_URL
