apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: journiv-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  target:
    name: journiv-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: JOURNIV_SECRET
